let autofill = [
    "George Orwell",
    "William Golding",
    "Ian McEwan",
    "Madeline Miller",
    "Stephen King",
    "Celeste Ng",
    "J.K. Rowling",
    "Circe",
    "Atonement",
    "1984",
    "Harry Potter",
    "Emily Bronte",
    "Charlotte Bronte",
    "Jane Eyre",
    "Wuthering Heights",
    "The Green Mile",
    "Animal Farm",
    "Ken Follet",
    "A Dangerous Fortune",
    "Lord of the Flies",
    "Harry Potter",
    "Bob Goff",
    "Dune",
    "A song of Ice and Fire",
    "George R. R. Martin",
    "Heinreich Boll",
    "The Clown",
    "Crime and Punishment"
]